CREATE TABLE [dbo].[Customer]
(
	[customerId] INT NOT NULL PRIMARY KEY DEFAULT 0, 
    [firstName] VARCHAR(25) NOT NULL DEFAULT '', 
    [lastName] VARCHAR(30) NOT NULL DEFAULT '', 
	[companyName] VARCHAR(50) NULL DEFAULT '', 
	[unitNumber01] INT NULL DEFAULT 0, 
    [streetNumber01] INT NOT NULL DEFAULT 0, 
    [streetName_01] VARCHAR(50) NOT NULL DEFAULT '', 
    [postalCode_01] VARCHAR(10) NOT NULL DEFAULT '', 
	[unitNumber_02] INT NULL DEFAULT 0, 
    [streetNumber_02] INT NULL DEFAULT 0, 
    [streetName_02] VARCHAR(50) NULL DEFAULT '', 
    [postalCode_02] VARCHAR(10) NULL DEFAULT '', 
	[cityId_01] INT NOT NULL DEFAULT 0, 
	[cityId_02] INT NULL DEFAULT 0,
	[bussinessPhone] BIGINT NULL DEFAULT 0, 
	[contactPhone] BIGINT NOT NULL DEFAULT 0,
	[fax] BIGINT NULL DEFAULT 0, 
    [contactMobile] BIGINT NULL DEFAULT 0000000000, 
    [contactName] VARCHAR(255) NULL DEFAULT '',
    [comments] VARCHAR(255) NULL DEFAULT '',
    [DateActive] DATE NULL DEFAULT 0000-00-00, 
    [DateModified] DATE NULL DEFAULT 0000-00-00, 
	[contactEmail] VARCHAR(100) NULL DEFAULT '', 
    CONSTRAINT [FK_Customer_City] FOREIGN KEY (cityId) REFERENCES [city](cityId)
)
